from __future__ import annotations

from typing import Protocol, Optional
from typing_extensions import runtime_checkable

@runtime_checkable
class ControlledMechanicalVentilationDevice(Protocol):
    """Interfaccia per un device 'Controlled Mechanical Ventilation' controllabile."""

    async def async_set_power(self, *, power: Optional[bool] = None) -> None: ...
    async def async_set_processing_mode(self, mode: Optional[str] = None) -> None: ...

    async def async_set_spare(self, spare: Optional[int] = None) -> None: ...

    async def async_set_temperature(self, target: Optional[float] = None) -> None: ...
    async def async_set_humidity(self, target: Optional[float] = None) -> None: ...
    async def async_set_dew_point(self, target: Optional[float] = None) -> None: ...
    async def async_set_delta_dew_point(self, target: Optional[int] = None) -> None: ...

    # Free cooling ventilativo (bypass recuperatore)
    async def async_set_treatment_off(self, value: Optional[bool] = None) -> None: ...
    """Coil 3 — disabilita trattamento termico (prerequisito per free cooling)."""

    async def async_enable_free_cooling(self, value: Optional[bool] = None) -> None: ...
    """Coil 9 — abilita forzatura free-cooling."""

    async def async_set_free_cooling(self, value: Optional[bool] = None) -> None: ...
    """Coil 10 — attiva bypass recuperatore."""



