from __future__ import annotations

from typing import Protocol, Optional, Any
from typing_extensions import runtime_checkable

@runtime_checkable
class ControlledMechanicalVentilationDevice(Protocol):
    """Interfaccia per un device 'Controlled Mechanical Ventilation' controllabile."""

    async def async_set_power(self, *, power: Optional[bool] = None) -> None: ...
    async def async_set_processing_mode(self, mode: Optional[str] = None) -> None: ...

    async def async_set_spare(self, spare: Optional[int] = None) -> None: ...

    async def async_set_temperature(self, target: Optional[float] = None) -> None: ...
    async def async_set_humidity(self, target: Optional[float] = None) -> None: ...
    async def async_set_dew_point(self, target: Optional[float] = None) -> None: ...
    async def async_set_delta_dew_point(self, target: Optional[int] = None) -> None: ...




